# NOTE: update this with your service name
service: beesafe-backend

# Create an optimized package for our functions
package:
  individually: true
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - 'prisma/**'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-webpack-prisma
  - serverless-plugin-typescript

custom:
  webpack:
    packagerOptions:
      scripts:
        - prisma generate
        - find . -name "libquery_engine-*" -not -name "libquery_engine-arm64-openssl-*" | xargs rm

disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  profile: default
  
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
    package:
      include:
        - ./prisma/schema.prisma
        - './node_modules/.prisma/client/libquery_engine-*'
        - './node_modules/prisma/libquery_engine-*'