# NOTE: update this with your service name
service: beesafe-backend

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

disabledDeprecations:
  - "*" # To disable all deprecation messages

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  profile: default
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_DB_NAME: ${env:PG_DB_NAME}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_PORT: ${env:PG_PORT}
    tableName: notes

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
